apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  namespace: smart-ui      
  labels:
    app: smart-ui
spec:
  replicas: 1 #The number of pods to be created in the 
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: smart-ui
  template:
    metadata:
      labels:
        app: smart-ui 
      annotations:
        kubernetes.io/change-cause: "Updated deployment"  
    spec:
      containers:
      - name: smart-ui #The name of the react.js application container
        #The Docker image for building the React.js application container
        image: iamlavityagi/smart-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 #The port for the React.js application container