apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: smart-ui-service 
  namespace: smart-ui
spec:
  selector:
    app: smart-ui 
  type: ClusterIP #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 3000 #The port for the React.js application container